# Generated by Django 5.1.4 on 2025-01-13 06:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('location', models.CharField(max_length=255, verbose_name='Местоположение')),
                ('rating', models.FloatField(verbose_name='Рейтинг')),
                ('price_per_night', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Стоимость за ночь')),
                ('image', models.ImageField(blank=True, null=True, upload_to='hotel_images/', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Отель',
                'verbose_name_plural': 'Отели',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='Номер комнаты')),
                ('room_type', models.CharField(choices=[('Standard', 'Стандарт'), ('Luxury', 'Люкс'), ('Apartment', 'Апартаменты')], max_length=50, verbose_name='Тип номера')),
                ('capacity', models.PositiveIntegerField(verbose_name='Вместимость')),
                ('available', models.BooleanField(default=True, verbose_name='Доступность')),
                ('price_per_night', models.DecimalField(decimal_places=2, default=100.0, max_digits=10, verbose_name='Стоимость за ночь')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotels.hotel', verbose_name='Отель')),
            ],
            options={
                'verbose_name': 'Номер',
                'verbose_name_plural': 'Номера',
                'ordering': ['room_number'],
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.DateField(verbose_name='Дата заезда')),
                ('check_out', models.DateField(verbose_name='Дата выезда')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Общая цена')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotels.room', verbose_name='Комната')),
            ],
            options={
                'verbose_name': 'Бронирование',
                'verbose_name_plural': 'Бронирования',
            },
        ),
    ]
