# Generated by Django 5.1.4 on 2025-01-13 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0002_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='room',
        ),
    ]
